-keep class androidx.core.app.ActivityCompat { *; }
-keep class androidx.core.app.ActivityOptionsCompat { *; }
-keep class androidx.core.content.ContextCompat { *; }
-keep class dev.hebei.wifi.** { *; }
-keep class io.flutter.plugin.common.PluginRegistry { *; }