// Autogenerated from Pigeon (v24.2.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.hebei.wifi

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is WifiError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): WifiError {
  return WifiError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class WifiError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()
/**
 * Maintains instances used to communicate with the corresponding objects in Dart.
 *
 * Objects stored in this container are represented by an object in Dart that is also stored in
 * an InstanceManager with the same identifier.
 *
 * When an instance is added with an identifier, either can be used to retrieve the other.
 *
 * Added instances are added as a weak reference and a strong reference. When the strong
 * reference is removed with [remove] and the weak reference is deallocated, the
 * `finalizationListener.onFinalize` is called with the instance's identifier. However, if the strong
 * reference is removed and then the identifier is retrieved with the intention to pass the identifier
 * to Dart (e.g. calling [getIdentifierForStrongReference]), the strong reference to the instance
 * is recreated. The strong reference will then need to be removed manually again.
 */
@Suppress("UNCHECKED_CAST", "MemberVisibilityCanBePrivate")
class WifiPigeonInstanceManager(private val finalizationListener: PigeonFinalizationListener) {
  /** Interface for listening when a weak reference of an instance is removed from the manager.  */
  interface PigeonFinalizationListener {
    fun onFinalize(identifier: Long)
  }

  private val identifiers = java.util.WeakHashMap<Any, Long>()
  private val weakInstances = HashMap<Long, java.lang.ref.WeakReference<Any>>()
  private val strongInstances = HashMap<Long, Any>()
  private val referenceQueue = java.lang.ref.ReferenceQueue<Any>()
  private val weakReferencesToIdentifiers = HashMap<java.lang.ref.WeakReference<Any>, Long>()
  private val handler = android.os.Handler(android.os.Looper.getMainLooper())
  private var nextIdentifier: Long = minHostCreatedIdentifier
  private var hasFinalizationListenerStopped = false

  /**
   * Modifies the time interval used to define how often this instance removes garbage collected
   * weak references to native Android objects that this instance was managing.
   */
  var clearFinalizedWeakReferencesInterval: Long = 3000
    set(value) {
      handler.removeCallbacks { this.releaseAllFinalizedInstances() }
      field = value
      releaseAllFinalizedInstances()
    }

  init {
    handler.postDelayed(
      { releaseAllFinalizedInstances() },
      clearFinalizedWeakReferencesInterval
    )
  }

  companion object {
    // Identifiers are locked to a specific range to avoid collisions with objects
    // created simultaneously from Dart.
    // Host uses identifiers >= 2^16 and Dart is expected to use values n where,
    // 0 <= n < 2^16.
    private const val minHostCreatedIdentifier: Long = 65536
    private const val tag = "PigeonInstanceManager"

    /**
     * Instantiate a new manager with a listener for garbage collected weak
     * references.
     *
     * When the manager is no longer needed, [stopFinalizationListener] must be called.
     */
    fun create(finalizationListener: PigeonFinalizationListener): WifiPigeonInstanceManager {
      return WifiPigeonInstanceManager(finalizationListener)
    }
  }

  /**
   * Removes `identifier` and return its associated strongly referenced instance, if present,
   * from the manager.
   */
  fun <T> remove(identifier: Long): T? {
    logWarningIfFinalizationListenerHasStopped()
    return strongInstances.remove(identifier) as T?
  }

  /**
   * Retrieves the identifier paired with an instance, if present, otherwise `null`.
   *
   *
   * If the manager contains a strong reference to `instance`, it will return the identifier
   * associated with `instance`. If the manager contains only a weak reference to `instance`, a new
   * strong reference to `instance` will be added and will need to be removed again with [remove].
   *
   *
   * If this method returns a nonnull identifier, this method also expects the Dart
   * `WifiPigeonInstanceManager` to have, or recreate, a weak reference to the Dart instance the
   * identifier is associated with.
   */
  fun getIdentifierForStrongReference(instance: Any?): Long? {
    logWarningIfFinalizationListenerHasStopped()
    val identifier = identifiers[instance]
    if (identifier != null) {
      strongInstances[identifier] = instance!!
    }
    return identifier
  }

  /**
   * Adds a new instance that was instantiated from Dart.
   *
   * The same instance can be added multiple times, but each identifier must be unique. This
   * allows two objects that are equivalent (e.g. the `equals` method returns true and their
   * hashcodes are equal) to both be added.
   *
   * [identifier] must be >= 0 and unique.
   */
  fun addDartCreatedInstance(instance: Any, identifier: Long) {
    logWarningIfFinalizationListenerHasStopped()
    addInstance(instance, identifier)
  }

  /**
   * Adds a new unique instance that was instantiated from the host platform.
   *
   * [identifier] must be >= 0 and unique.
   */
  fun addHostCreatedInstance(instance: Any): Long {
    logWarningIfFinalizationListenerHasStopped()
    require(!containsInstance(instance)) { "Instance of ${instance.javaClass} has already been added." }
    val identifier = nextIdentifier++
    addInstance(instance, identifier)
    return identifier
  }

  /** Retrieves the instance associated with identifier, if present, otherwise `null`. */
  fun <T> getInstance(identifier: Long): T? {
    logWarningIfFinalizationListenerHasStopped()
    val instance = weakInstances[identifier] as java.lang.ref.WeakReference<T>?
    return instance?.get()
  }

  /** Returns whether this manager contains the given `instance`. */
  fun containsInstance(instance: Any?): Boolean {
    logWarningIfFinalizationListenerHasStopped()
    return identifiers.containsKey(instance)
  }

  /**
   * Stops the periodic run of the [PigeonFinalizationListener] for instances that have been garbage
   * collected.
   *
   * The InstanceManager can continue to be used, but the [PigeonFinalizationListener] will no
   * longer be called and methods will log a warning.
   */
  fun stopFinalizationListener() {
    handler.removeCallbacks { this.releaseAllFinalizedInstances() }
    hasFinalizationListenerStopped = true
  }

  /**
   * Removes all of the instances from this manager.
   *
   * The manager will be empty after this call returns.
   */
  fun clear() {
    identifiers.clear()
    weakInstances.clear()
    strongInstances.clear()
    weakReferencesToIdentifiers.clear()
  }

  /**
   * Whether the [PigeonFinalizationListener] is still being called for instances that are garbage
   * collected.
   *
   * See [stopFinalizationListener].
   */
  fun hasFinalizationListenerStopped(): Boolean {
    return hasFinalizationListenerStopped
  }

  private fun releaseAllFinalizedInstances() {
    if (hasFinalizationListenerStopped()) {
      return
    }
    var reference: java.lang.ref.WeakReference<Any>?
    while ((referenceQueue.poll() as java.lang.ref.WeakReference<Any>?).also { reference = it } != null) {
      val identifier = weakReferencesToIdentifiers.remove(reference)
      if (identifier != null) {
        weakInstances.remove(identifier)
        strongInstances.remove(identifier)
        finalizationListener.onFinalize(identifier)
      }
    }
    handler.postDelayed(
      { releaseAllFinalizedInstances() },
      clearFinalizedWeakReferencesInterval
    )
  }

  private fun addInstance(instance: Any, identifier: Long) {
    require(identifier >= 0) { "Identifier must be >= 0: $identifier" }
    require(!weakInstances.containsKey(identifier)) {
      "Identifier has already been added: $identifier"
    }
    val weakReference = java.lang.ref.WeakReference(instance, referenceQueue)
    identifiers[instance] = identifier
    weakInstances[identifier] = weakReference
    weakReferencesToIdentifiers[weakReference] = identifier
    strongInstances[identifier] = instance
  }

  private fun logWarningIfFinalizationListenerHasStopped() {
    if (hasFinalizationListenerStopped()) {
      Log.w(
        tag,
        "The manager was used after calls to the PigeonFinalizationListener has been stopped."
      )
    }
  }
}


/** Generated API for managing the Dart and native `InstanceManager`s. */
private class WifiPigeonInstanceManagerApi(val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by WifiPigeonInstanceManagerApi. */
    val codec: MessageCodec<Any?> by lazy {
      WifiPigeonCodec()
    }

    /**
     * Sets up an instance of `WifiPigeonInstanceManagerApi` to handle messages from the
     * `binaryMessenger`.
     */
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, instanceManager: WifiPigeonInstanceManager?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.PigeonInternalInstanceManager.removeStrongReference", codec)
        if (instanceManager != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val identifierArg = args[0] as Long
            val wrapped: List<Any?> = try {
              instanceManager.remove<Any?>(identifierArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.PigeonInternalInstanceManager.clear", codec)
        if (instanceManager != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              instanceManager.clear()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  fun removeStrongReference(identifierArg: Long, callback: (Result<Unit>) -> Unit)
{
    val channelName = "dev.flutter.pigeon.wifi.PigeonInternalInstanceManager.removeStrongReference"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(identifierArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(WifiError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
/**
 * Provides implementations for each ProxyApi implementation and provides access to resources
 * needed by any implementation.
 */
abstract class WifiPigeonProxyApiRegistrar(val binaryMessenger: BinaryMessenger) {
  /** Whether APIs should ignore calling to Dart. */
  public var ignoreCallsToDart = false
  val instanceManager: WifiPigeonInstanceManager
  private var _codec: MessageCodec<Any?>? = null
  val codec: MessageCodec<Any?>
    get() {
      if (_codec == null) {
        _codec = WifiPigeonProxyApiBaseCodec(this)
      }
      return _codec!!
    }

  init {
    val api = WifiPigeonInstanceManagerApi(binaryMessenger)
    instanceManager = WifiPigeonInstanceManager.create(
      object : WifiPigeonInstanceManager.PigeonFinalizationListener {
        override fun onFinalize(identifier: Long) {
          api.removeStrongReference(identifier) {
            if (it.isFailure) {
              Log.e(
                "PigeonProxyApiRegistrar",
                "Failed to remove Dart strong reference with identifier: $identifier"
              )
            }
          }
        }
      }
    )
  }
  /**
   * An implementation of [PigeonApiWifiPlugin] used to add a new Dart instance of
   * `WifiPlugin` to the Dart `InstanceManager`.
   */
  abstract fun getPigeonApiWifiPlugin(): PigeonApiWifiPlugin

  /**
   * An implementation of [PigeonApiContext] used to add a new Dart instance of
   * `Context` to the Dart `InstanceManager`.
   */
  abstract fun getPigeonApiContext(): PigeonApiContext

  /**
   * An implementation of [PigeonApiContextCompat] used to add a new Dart instance of
   * `ContextCompat` to the Dart `InstanceManager`.
   */
  abstract fun getPigeonApiContextCompat(): PigeonApiContextCompat

  /**
   * An implementation of [PigeonApiIntent] used to add a new Dart instance of
   * `Intent` to the Dart `InstanceManager`.
   */
  abstract fun getPigeonApiIntent(): PigeonApiIntent

  /**
   * An implementation of [PigeonApiBroadcastReceiver] used to add a new Dart instance of
   * `BroadcastReceiver` to the Dart `InstanceManager`.
   */
  abstract fun getPigeonApiBroadcastReceiver(): PigeonApiBroadcastReceiver

  /**
   * An implementation of [PigeonApiIntentFilter] used to add a new Dart instance of
   * `IntentFilter` to the Dart `InstanceManager`.
   */
  abstract fun getPigeonApiIntentFilter(): PigeonApiIntentFilter

  /**
   * An implementation of [PigeonApiWifiManager] used to add a new Dart instance of
   * `WifiManager` to the Dart `InstanceManager`.
   */
  abstract fun getPigeonApiWifiManager(): PigeonApiWifiManager

  /**
   * An implementation of [PigeonApiWifiConfiguration] used to add a new Dart instance of
   * `WifiConfiguration` to the Dart `InstanceManager`.
   */
  abstract fun getPigeonApiWifiConfiguration(): PigeonApiWifiConfiguration

  /**
   * An implementation of [PigeonApiWifiInfo] used to add a new Dart instance of
   * `WifiInfo` to the Dart `InstanceManager`.
   */
  abstract fun getPigeonApiWifiInfo(): PigeonApiWifiInfo

  /**
   * An implementation of [PigeonApiDhcpInfo] used to add a new Dart instance of
   * `DhcpInfo` to the Dart `InstanceManager`.
   */
  abstract fun getPigeonApiDhcpInfo(): PigeonApiDhcpInfo

  fun setUp() {
    WifiPigeonInstanceManagerApi.setUpMessageHandlers(binaryMessenger, instanceManager)
    PigeonApiWifiPlugin.setUpMessageHandlers(binaryMessenger, getPigeonApiWifiPlugin())
    PigeonApiContext.setUpMessageHandlers(binaryMessenger, getPigeonApiContext())
    PigeonApiContextCompat.setUpMessageHandlers(binaryMessenger, getPigeonApiContextCompat())
    PigeonApiIntent.setUpMessageHandlers(binaryMessenger, getPigeonApiIntent())
    PigeonApiBroadcastReceiver.setUpMessageHandlers(binaryMessenger, getPigeonApiBroadcastReceiver())
    PigeonApiIntentFilter.setUpMessageHandlers(binaryMessenger, getPigeonApiIntentFilter())
    PigeonApiWifiManager.setUpMessageHandlers(binaryMessenger, getPigeonApiWifiManager())
    PigeonApiWifiConfiguration.setUpMessageHandlers(binaryMessenger, getPigeonApiWifiConfiguration())
    PigeonApiWifiInfo.setUpMessageHandlers(binaryMessenger, getPigeonApiWifiInfo())
    PigeonApiDhcpInfo.setUpMessageHandlers(binaryMessenger, getPigeonApiDhcpInfo())
  }
  fun tearDown() {
    WifiPigeonInstanceManagerApi.setUpMessageHandlers(binaryMessenger, null)
    PigeonApiWifiPlugin.setUpMessageHandlers(binaryMessenger, null)
    PigeonApiContext.setUpMessageHandlers(binaryMessenger, null)
    PigeonApiContextCompat.setUpMessageHandlers(binaryMessenger, null)
    PigeonApiIntent.setUpMessageHandlers(binaryMessenger, null)
    PigeonApiBroadcastReceiver.setUpMessageHandlers(binaryMessenger, null)
    PigeonApiIntentFilter.setUpMessageHandlers(binaryMessenger, null)
    PigeonApiWifiManager.setUpMessageHandlers(binaryMessenger, null)
    PigeonApiWifiConfiguration.setUpMessageHandlers(binaryMessenger, null)
    PigeonApiWifiInfo.setUpMessageHandlers(binaryMessenger, null)
    PigeonApiDhcpInfo.setUpMessageHandlers(binaryMessenger, null)
  }
}
private class WifiPigeonProxyApiBaseCodec(val registrar: WifiPigeonProxyApiRegistrar) : WifiPigeonCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        val identifier: Long = readValue(buffer) as Long
        val instance: Any? = registrar.instanceManager.getInstance(identifier)
        if (instance == null) {
          Log.e(
            "PigeonProxyApiBaseCodec",
            "Failed to find instance with identifier: $identifier"
          )
        }
        return instance
      }
      else -> super.readValueOfType(type, buffer)
    }
  }

  override fun writeValue(stream: ByteArrayOutputStream, value: Any?) {
    if (value is Boolean || value is ByteArray || value is Double || value is DoubleArray || value is FloatArray || value is Int || value is IntArray || value is List<*> || value is Long || value is LongArray || value is Map<*, *> || value is String || value is ReceiverFlags || value is IntentAction || value is WifiState || value is WifiConfigurationStatus || value == null) {
      super.writeValue(stream, value)
      return
    }

    if (value is dev.hebei.wifi.WifiPlugin) {
      registrar.getPigeonApiWifiPlugin().pigeon_newInstance(value) { }
    }
     else if (value is android.content.Context) {
      registrar.getPigeonApiContext().pigeon_newInstance(value) { }
    }
     else if (value is androidx.core.content.ContextCompat) {
      registrar.getPigeonApiContextCompat().pigeon_newInstance(value) { }
    }
     else if (value is android.content.Intent) {
      registrar.getPigeonApiIntent().pigeon_newInstance(value) { }
    }
     else if (value is android.content.BroadcastReceiver) {
      registrar.getPigeonApiBroadcastReceiver().pigeon_newInstance(value) { }
    }
     else if (value is android.content.IntentFilter) {
      registrar.getPigeonApiIntentFilter().pigeon_newInstance(value) { }
    }
     else if (value is android.net.wifi.WifiManager) {
      registrar.getPigeonApiWifiManager().pigeon_newInstance(value) { }
    }
     else if (value is android.net.wifi.WifiConfiguration) {
      registrar.getPigeonApiWifiConfiguration().pigeon_newInstance(value) { }
    }
     else if (value is android.net.wifi.WifiInfo) {
      registrar.getPigeonApiWifiInfo().pigeon_newInstance(value) { }
    }
     else if (value is android.net.DhcpInfo) {
      registrar.getPigeonApiDhcpInfo().pigeon_newInstance(value) { }
    }

    when {
      registrar.instanceManager.containsInstance(value) -> {
        stream.write(128)
        writeValue(stream, registrar.instanceManager.getIdentifierForStrongReference(value))
      }
      else -> throw IllegalArgumentException("Unsupported value: '$value' of type '${value.javaClass.name}'")
    }
  }
}

enum class ReceiverFlags(val raw: Int) {
  EXPORTED(0),
  NOT_EXPORTED(1),
  VISIBLE_TO_INSTANT_APPS(2);

  companion object {
    fun ofRaw(raw: Int): ReceiverFlags? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class IntentAction(val raw: Int) {
  UNKNOWN(0),
  WIFI_STATE_CHANGED(1);

  companion object {
    fun ofRaw(raw: Int): IntentAction? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class WifiState(val raw: Int) {
  UNKNOWN(0),
  DISABLED(1),
  DISABLING(2),
  ENABLED(3),
  ENABLING(4);

  companion object {
    fun ofRaw(raw: Int): WifiState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class WifiConfigurationStatus(val raw: Int) {
  CURRENT(0),
  DISABLED(1),
  ENABLED(2);

  companion object {
    fun ofRaw(raw: Int): WifiConfigurationStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}
private open class WifiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ReceiverFlags.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          IntentAction.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          WifiState.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          WifiConfigurationStatus.ofRaw(it.toInt())
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ReceiverFlags -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is IntentAction -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is WifiState -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is WifiConfigurationStatus -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      else -> super.writeValue(stream, value)
    }
  }
}

@Suppress("UNCHECKED_CAST")
abstract class PigeonApiWifiPlugin(open val pigeonRegistrar: WifiPigeonProxyApiRegistrar) {
  abstract fun instance(): dev.hebei.wifi.WifiPlugin

  abstract fun context(pigeon_instance: dev.hebei.wifi.WifiPlugin): android.content.Context

  companion object {
    @Suppress("LocalVariableName")
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, api: PigeonApiWifiPlugin?) {
      val codec = api?.pigeonRegistrar?.codec ?: WifiPigeonCodec()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiPlugin.instance", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_identifierArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.pigeonRegistrar.instanceManager.addDartCreatedInstance(api.instance(), pigeon_identifierArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiPlugin.context", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as dev.hebei.wifi.WifiPlugin
            val pigeon_identifierArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.pigeonRegistrar.instanceManager.addDartCreatedInstance(api.context(pigeon_instanceArg), pigeon_identifierArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of WifiPlugin and attaches it to [pigeon_instanceArg]. */
  fun pigeon_newInstance(pigeon_instanceArg: dev.hebei.wifi.WifiPlugin, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              WifiError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      val pigeon_identifierArg = pigeonRegistrar.instanceManager.addHostCreatedInstance(pigeon_instanceArg)
      val binaryMessenger = pigeonRegistrar.binaryMessenger
      val codec = pigeonRegistrar.codec
      val channelName = "dev.flutter.pigeon.wifi.WifiPlugin.pigeon_newInstance"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(pigeon_identifierArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            callback(Result.failure(WifiError(it[0] as String, it[1] as String, it[2] as String?)))
          } else {
            callback(Result.success(Unit))
          }
        } else {
          callback(Result.failure(createConnectionError(channelName)))
        } 
      }
    }
  }

}
/**
 * Interface to global information about an application environment. This is an
 * abstract class whose implementation is provided by the Android system. It
 * allows access to application-specific resources and classes, as well as up-calls
 * for application-level operations such as launching activities, broadcasting
 * and receiving intents, etc.
 */
@Suppress("UNCHECKED_CAST")
abstract class PigeonApiContext(open val pigeonRegistrar: WifiPigeonProxyApiRegistrar) {
  /**
   * Unregister a previously registered BroadcastReceiver. All filters that have
   * been registered for this BroadcastReceiver will be removed.
   */
  abstract fun unregisterReceiver(pigeon_instance: android.content.Context, receiver: android.content.BroadcastReceiver)

  companion object {
    @Suppress("LocalVariableName")
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, api: PigeonApiContext?) {
      val codec = api?.pigeonRegistrar?.codec ?: WifiPigeonCodec()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.Context.unregisterReceiver", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.content.Context
            val receiverArg = args[1] as android.content.BroadcastReceiver
            val wrapped: List<Any?> = try {
              api.unregisterReceiver(pigeon_instanceArg, receiverArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of Context and attaches it to [pigeon_instanceArg]. */
  fun pigeon_newInstance(pigeon_instanceArg: android.content.Context, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              WifiError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      val pigeon_identifierArg = pigeonRegistrar.instanceManager.addHostCreatedInstance(pigeon_instanceArg)
      val binaryMessenger = pigeonRegistrar.binaryMessenger
      val codec = pigeonRegistrar.codec
      val channelName = "dev.flutter.pigeon.wifi.Context.pigeon_newInstance"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(pigeon_identifierArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            callback(Result.failure(WifiError(it[0] as String, it[1] as String, it[2] as String?)))
          } else {
            callback(Result.success(Unit))
          }
        } else {
          callback(Result.failure(createConnectionError(channelName)))
        } 
      }
    }
  }

}
/** Helper for accessing features in Context. */
@Suppress("UNCHECKED_CAST")
abstract class PigeonApiContextCompat(open val pigeonRegistrar: WifiPigeonProxyApiRegistrar) {
  /** Return the handle to a system-level service by class. */
  abstract fun getWifiManager(context: android.content.Context): android.net.wifi.WifiManager?

  /** Register a broadcast receiver. */
  abstract fun registerReceiver(context: android.content.Context, receiver: android.content.BroadcastReceiver, filter: android.content.IntentFilter, flags: ReceiverFlags): android.content.Intent?

  companion object {
    @Suppress("LocalVariableName")
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, api: PigeonApiContextCompat?) {
      val codec = api?.pigeonRegistrar?.codec ?: WifiPigeonCodec()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.ContextCompat.getWifiManager", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val contextArg = args[0] as android.content.Context
            val wrapped: List<Any?> = try {
              listOf(api.getWifiManager(contextArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.ContextCompat.registerReceiver", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val contextArg = args[0] as android.content.Context
            val receiverArg = args[1] as android.content.BroadcastReceiver
            val filterArg = args[2] as android.content.IntentFilter
            val flagsArg = args[3] as ReceiverFlags
            val wrapped: List<Any?> = try {
              listOf(api.registerReceiver(contextArg, receiverArg, filterArg, flagsArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of ContextCompat and attaches it to [pigeon_instanceArg]. */
  fun pigeon_newInstance(pigeon_instanceArg: androidx.core.content.ContextCompat, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              WifiError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      val pigeon_identifierArg = pigeonRegistrar.instanceManager.addHostCreatedInstance(pigeon_instanceArg)
      val binaryMessenger = pigeonRegistrar.binaryMessenger
      val codec = pigeonRegistrar.codec
      val channelName = "dev.flutter.pigeon.wifi.ContextCompat.pigeon_newInstance"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(pigeon_identifierArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            callback(Result.failure(WifiError(it[0] as String, it[1] as String, it[2] as String?)))
          } else {
            callback(Result.success(Unit))
          }
        } else {
          callback(Result.failure(createConnectionError(channelName)))
        } 
      }
    }
  }

}
/**
 * An intent is an abstract description of an operation to be performed. It can
 * be used with startActivity to launch an Activity, broadcastIntent to send it
 * to any interested BroadcastReceiver components, and Context.startService(Intent)
 * or Context.bindService(Intent, BindServiceFlags, Executor, ServiceConnection)
 * to communicate with a background Service.
 *
 * An Intent provides a facility for performing late runtime binding between the
 * code in different applications. Its most significant use is in the launching
 * of activities, where it can be thought of as the glue between activities. It
 * is basically a passive data structure holding an abstract description of an
 * action to be performed.
 */
@Suppress("UNCHECKED_CAST")
abstract class PigeonApiIntent(open val pigeonRegistrar: WifiPigeonProxyApiRegistrar) {
  /**
   * Retrieve the general action to be performed, such as ACTION_VIEW. The action
   * describes the general way the rest of the information in the intent should
   * be interpreted -- most importantly, what to do with the data returned by
   * getData().
   */
  abstract fun getAction(pigeon_instance: android.content.Intent): IntentAction

  abstract fun getWifiState(pigeon_instance: android.content.Intent): WifiState

  companion object {
    @Suppress("LocalVariableName")
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, api: PigeonApiIntent?) {
      val codec = api?.pigeonRegistrar?.codec ?: WifiPigeonCodec()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.Intent.getAction", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.content.Intent
            val wrapped: List<Any?> = try {
              listOf(api.getAction(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.Intent.getWifiState", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.content.Intent
            val wrapped: List<Any?> = try {
              listOf(api.getWifiState(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of Intent and attaches it to [pigeon_instanceArg]. */
  fun pigeon_newInstance(pigeon_instanceArg: android.content.Intent, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              WifiError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      val pigeon_identifierArg = pigeonRegistrar.instanceManager.addHostCreatedInstance(pigeon_instanceArg)
      val binaryMessenger = pigeonRegistrar.binaryMessenger
      val codec = pigeonRegistrar.codec
      val channelName = "dev.flutter.pigeon.wifi.Intent.pigeon_newInstance"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(pigeon_identifierArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            callback(Result.failure(WifiError(it[0] as String, it[1] as String, it[2] as String?)))
          } else {
            callback(Result.success(Unit))
          }
        } else {
          callback(Result.failure(createConnectionError(channelName)))
        } 
      }
    }
  }

}
/**
 * Base class for code that receives and handles broadcast intents sent by
 * Context.sendBroadcast(Intent).
 *
 * You can either dynamically register an instance of this class with
 * Context.registerReceiver() or statically declare an implementation with the
 * &lt;receiver&gt; tag in your AndroidManifest.xml.
 */
@Suppress("UNCHECKED_CAST")
abstract class PigeonApiBroadcastReceiver(open val pigeonRegistrar: WifiPigeonProxyApiRegistrar) {
  abstract fun pigeon_defaultConstructor(): android.content.BroadcastReceiver

  companion object {
    @Suppress("LocalVariableName")
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, api: PigeonApiBroadcastReceiver?) {
      val codec = api?.pigeonRegistrar?.codec ?: WifiPigeonCodec()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.BroadcastReceiver.pigeon_defaultConstructor", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_identifierArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.pigeonRegistrar.instanceManager.addDartCreatedInstance(api.pigeon_defaultConstructor(), pigeon_identifierArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of BroadcastReceiver and attaches it to [pigeon_instanceArg]. */
  fun pigeon_newInstance(pigeon_instanceArg: android.content.BroadcastReceiver, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              WifiError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      callback(
          Result.failure(
              WifiError("new-instance-error", "Attempting to create a new Dart instance of BroadcastReceiver, but the class has a nonnull callback method.", "")))
    }
  }

  /** This method is called when the BroadcastReceiver is receiving an Intent broadcast. During this time you can use the other methods on BroadcastReceiver to view/modify the current result values. This method is always called within the main thread of its process, unless you explicitly asked for it to be scheduled on a different thread using Context.registerReceiver(BroadcastReceiver, IntentFilter, String, android.os.Handler). When it runs on the main thread you should never perform long-running operations in it (there is a timeout of 10 seconds that the system allows before considering the receiver to be blocked and a candidate to be killed). You cannot launch a popup dialog in your implementation of onReceive(). */
  fun onReceive(pigeon_instanceArg: android.content.BroadcastReceiver, contextArg: android.content.Context, intentArg: android.content.Intent, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              WifiError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
      return
    }
    val binaryMessenger = pigeonRegistrar.binaryMessenger
    val codec = pigeonRegistrar.codec
    val channelName = "dev.flutter.pigeon.wifi.BroadcastReceiver.onReceive"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(pigeon_instanceArg, contextArg, intentArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(WifiError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }

}
/**
 * Structured description of Intent values to be matched. An IntentFilter can
 * match against actions, categories, and data (either via its type, scheme,
 * and/or path) in an Intent. It also includes a "priority" value which is used
 * to order multiple matching filters.
 */
@Suppress("UNCHECKED_CAST")
abstract class PigeonApiIntentFilter(open val pigeonRegistrar: WifiPigeonProxyApiRegistrar) {
  /**
   * New IntentFilter that matches a single action with no data. If no data
   * characteristics are subsequently specified, then the filter will only match
   * intents that contain no data.
   */
  abstract fun pigeon_defaultConstructor(action: IntentAction): android.content.IntentFilter

  companion object {
    @Suppress("LocalVariableName")
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, api: PigeonApiIntentFilter?) {
      val codec = api?.pigeonRegistrar?.codec ?: WifiPigeonCodec()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.IntentFilter.pigeon_defaultConstructor", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_identifierArg = args[0] as Long
            val actionArg = args[1] as IntentAction
            val wrapped: List<Any?> = try {
              api.pigeonRegistrar.instanceManager.addDartCreatedInstance(api.pigeon_defaultConstructor(actionArg), pigeon_identifierArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of IntentFilter and attaches it to [pigeon_instanceArg]. */
  fun pigeon_newInstance(pigeon_instanceArg: android.content.IntentFilter, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              WifiError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      val pigeon_identifierArg = pigeonRegistrar.instanceManager.addHostCreatedInstance(pigeon_instanceArg)
      val binaryMessenger = pigeonRegistrar.binaryMessenger
      val codec = pigeonRegistrar.codec
      val channelName = "dev.flutter.pigeon.wifi.IntentFilter.pigeon_newInstance"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(pigeon_identifierArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            callback(Result.failure(WifiError(it[0] as String, it[1] as String, it[2] as String?)))
          } else {
            callback(Result.success(Unit))
          }
        } else {
          callback(Result.failure(createConnectionError(channelName)))
        } 
      }
    }
  }

}
/**
 * This class provides the primary API for managing all aspects of Wi-Fi
 * connectivity.
 *
 * On releases before Build.VERSION_CODES.N, this object should only be obtained
 * from an application context, and not from any other derived context to avoid
 * memory leaks within the calling process.
 *
 * It deals with several categories of items:
 *
 * * The list of configured networks. The list can be viewed and updated, and
 * attributes of individual entries can be modified.
 * * The currently active Wi-Fi network, if any. Connectivity can be established
 * or torn down, and dynamic information about the state of the network can be
 * queried.
 * * Results of access point scans, containing enough information to make decisions
 * about what access point to connect to.
 * * It defines the names of various Intent actions that are broadcast upon any
 * sort of change in Wi-Fi state.
 *
 * This is the API to use when performing Wi-Fi specific operations. To perform
 * operations that pertain to network connectivity at an abstract level, use
 * ConnectivityManager.
 */
@Suppress("UNCHECKED_CAST")
abstract class PigeonApiWifiManager(open val pigeonRegistrar: WifiPigeonProxyApiRegistrar) {
  /**
   * Add a new network description to the set of configured networks. The networkId
   * field of the supplied configuration object is ignored.
   *
   * The new network will be marked DISABLED by default. To enable it, called
   * enableNetwork(int, boolean).
   */
  abstract fun addNetwork(pigeon_instance: android.net.wifi.WifiManager, config: android.net.wifi.WifiConfiguration): Long

  /**
   * Disable a configured network. The specified network will not be a candidate
   * for associating. This may result in the asynchronous delivery of state change
   * events. Applications are not allowed to disable networks created by other
   * applications.
   */
  abstract fun disableNetwork(pigeon_instance: android.net.wifi.WifiManager, netId: Long): Boolean

  /**
   * Disassociate from the currently active access point. This may result in the
   * asynchronous delivery of state change events.
   */
  abstract fun disconnect(pigeon_instance: android.net.wifi.WifiManager): Boolean

  /**
   * Allow a previously configured network to be associated with. If attemptConnect
   * is true, an attempt to connect to the selected network is initiated. This
   * may result in the asynchronous delivery of state change events.
   *
   * Note: Network communication may not use Wi-Fi even if Wi-Fi is connected;
   * traffic may instead be sent through another network, such as cellular data,
   * Bluetooth tethering, or Ethernet. For example, traffic will never use a Wi-Fi
   * network that does not provide Internet access (e.g. a wireless printer), if
   * another network that does offer Internet access (e.g. cellular data) is
   * available. Applications that need to ensure that their network traffic uses
   * Wi-Fi should use APIs such as Network.bindSocket(java.net.Socket),
   * Network.openConnection(java.net.URL), or ConnectivityManager.bindProcessToNetwork
   * to do so. Applications are not allowed to enable networks created by other
   * applications.
   */
  abstract fun enableNetwork(pigeon_instance: android.net.wifi.WifiManager, netId: Long, attemptConnect: Boolean): Boolean

  /**
   * Return a list of all the networks configured for the current foreground user.
   * Not all fields of WifiConfiguration are returned. Only the following fields are filled in:
   *
   * * networkId
   * * SSID
   * * BSSID
   * * priority
   * * allowedProtocols
   * * allowedKeyManagement
   * * allowedAuthAlgorithms
   * * allowedPairwiseCiphers
   * * allowedGroupCiphers
   * * status
   *
   * Requires android.Manifest.permission#ACCESS_FINE_LOCATION and
   * android.Manifest.permission#ACCESS_WIFI_STATE
   */
  abstract fun getConfiguredNetworks(pigeon_instance: android.net.wifi.WifiManager): List<android.net.wifi.WifiConfiguration>

  /**
   * Return dynamic information about the current Wi-Fi connection, if any is
   * active.
   */
  abstract fun getConnectionInfo(pigeon_instance: android.net.wifi.WifiManager): android.net.wifi.WifiInfo

  /**
   * Return the DHCP-assigned addresses from the last successful DHCP request,
   * if any.
   */
  abstract fun getDhcpInfo(pigeon_instance: android.net.wifi.WifiManager): android.net.DhcpInfo

  /** Return whether Wi-Fi is enabled or disabled. */
  abstract fun isWifiEnabled(pigeon_instance: android.net.wifi.WifiManager): Boolean

  /**
   * Enable or disable Wi-Fi.
   *
   * Applications must have the android.Manifest.permission#CHANGE_WIFI_STATE
   * permission to toggle wifi.
   */
  abstract fun setWifiEnabled(pigeon_instance: android.net.wifi.WifiManager, enabled: Boolean): Boolean

  companion object {
    @Suppress("LocalVariableName")
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, api: PigeonApiWifiManager?) {
      val codec = api?.pigeonRegistrar?.codec ?: WifiPigeonCodec()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiManager.addNetwork", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiManager
            val configArg = args[1] as android.net.wifi.WifiConfiguration
            val wrapped: List<Any?> = try {
              listOf(api.addNetwork(pigeon_instanceArg, configArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiManager.disableNetwork", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiManager
            val netIdArg = args[1] as Long
            val wrapped: List<Any?> = try {
              listOf(api.disableNetwork(pigeon_instanceArg, netIdArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiManager.disconnect", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiManager
            val wrapped: List<Any?> = try {
              listOf(api.disconnect(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiManager.enableNetwork", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiManager
            val netIdArg = args[1] as Long
            val attemptConnectArg = args[2] as Boolean
            val wrapped: List<Any?> = try {
              listOf(api.enableNetwork(pigeon_instanceArg, netIdArg, attemptConnectArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiManager.getConfiguredNetworks", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiManager
            val wrapped: List<Any?> = try {
              listOf(api.getConfiguredNetworks(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiManager.getConnectionInfo", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiManager
            val wrapped: List<Any?> = try {
              listOf(api.getConnectionInfo(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiManager.getDhcpInfo", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiManager
            val wrapped: List<Any?> = try {
              listOf(api.getDhcpInfo(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiManager.isWifiEnabled", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiManager
            val wrapped: List<Any?> = try {
              listOf(api.isWifiEnabled(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiManager.setWifiEnabled", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiManager
            val enabledArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              listOf(api.setWifiEnabled(pigeon_instanceArg, enabledArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of WifiManager and attaches it to [pigeon_instanceArg]. */
  fun pigeon_newInstance(pigeon_instanceArg: android.net.wifi.WifiManager, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              WifiError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      val pigeon_identifierArg = pigeonRegistrar.instanceManager.addHostCreatedInstance(pigeon_instanceArg)
      val binaryMessenger = pigeonRegistrar.binaryMessenger
      val codec = pigeonRegistrar.codec
      val channelName = "dev.flutter.pigeon.wifi.WifiManager.pigeon_newInstance"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(pigeon_identifierArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            callback(Result.failure(WifiError(it[0] as String, it[1] as String, it[2] as String?)))
          } else {
            callback(Result.success(Unit))
          }
        } else {
          callback(Result.failure(createConnectionError(channelName)))
        } 
      }
    }
  }

}
/**
 * A class representing a configured Wi-Fi network, including the security
 * configuration.
 */
@Suppress("UNCHECKED_CAST")
abstract class PigeonApiWifiConfiguration(open val pigeonRegistrar: WifiPigeonProxyApiRegistrar) {
  abstract fun pigeon_defaultConstructor(): android.net.wifi.WifiConfiguration

  /**
   * When set, this network configuration entry should only be used when associating
   * with the AP having the specified BSSID. The value is a string in the format
   * of an Ethernet MAC address, e.g., XX:XX:XX:XX:XX:XX where each X is a hex
   * digit.
   */
  abstract fun getBSSID(pigeon_instance: android.net.wifi.WifiConfiguration): String

  /** Fully qualified domain name of a Passpoint configuration */
  abstract fun getFQDN(pigeon_instance: android.net.wifi.WifiConfiguration): String

  /**
   * The network's SSID. Can either be a UTF-8 string, which must be enclosed in
   * double quotation marks (e.g., "MyNetwork"), or a string of hex digits, which
   * are not enclosed in quotes (e.g., 01a243f405).
   */
  abstract fun getSSID(pigeon_instance: android.net.wifi.WifiConfiguration): String

  abstract fun setSSID(pigeon_instance: android.net.wifi.WifiConfiguration, value: String)

  /**
   * This is a network that does not broadcast its SSID, so an SSID-specific probe
   * request must be used for scans.
   */
  abstract fun getHiddenSSID(pigeon_instance: android.net.wifi.WifiConfiguration): Boolean

  /**
   * The ID number that the supplicant uses to identify this network configuration
   * entry. This must be passed as an argument to most calls into the supplicant.
   */
  abstract fun getNetworkId(pigeon_instance: android.net.wifi.WifiConfiguration): Long

  /** The current status of this network configuration entry. */
  abstract fun getStatus(pigeon_instance: android.net.wifi.WifiConfiguration): WifiConfigurationStatus

  companion object {
    @Suppress("LocalVariableName")
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, api: PigeonApiWifiConfiguration?) {
      val codec = api?.pigeonRegistrar?.codec ?: WifiPigeonCodec()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiConfiguration.pigeon_defaultConstructor", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_identifierArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.pigeonRegistrar.instanceManager.addDartCreatedInstance(api.pigeon_defaultConstructor(), pigeon_identifierArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiConfiguration.getBSSID", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiConfiguration
            val wrapped: List<Any?> = try {
              listOf(api.getBSSID(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiConfiguration.getFQDN", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiConfiguration
            val wrapped: List<Any?> = try {
              listOf(api.getFQDN(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiConfiguration.getSSID", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiConfiguration
            val wrapped: List<Any?> = try {
              listOf(api.getSSID(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiConfiguration.setSSID", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiConfiguration
            val valueArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.setSSID(pigeon_instanceArg, valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiConfiguration.getHiddenSSID", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiConfiguration
            val wrapped: List<Any?> = try {
              listOf(api.getHiddenSSID(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiConfiguration.getNetworkId", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiConfiguration
            val wrapped: List<Any?> = try {
              listOf(api.getNetworkId(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiConfiguration.getStatus", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiConfiguration
            val wrapped: List<Any?> = try {
              listOf(api.getStatus(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of WifiConfiguration and attaches it to [pigeon_instanceArg]. */
  fun pigeon_newInstance(pigeon_instanceArg: android.net.wifi.WifiConfiguration, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              WifiError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      val pigeon_identifierArg = pigeonRegistrar.instanceManager.addHostCreatedInstance(pigeon_instanceArg)
      val binaryMessenger = pigeonRegistrar.binaryMessenger
      val codec = pigeonRegistrar.codec
      val channelName = "dev.flutter.pigeon.wifi.WifiConfiguration.pigeon_newInstance"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(pigeon_identifierArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            callback(Result.failure(WifiError(it[0] as String, it[1] as String, it[2] as String?)))
          } else {
            callback(Result.success(Unit))
          }
        } else {
          callback(Result.failure(createConnectionError(channelName)))
        } 
      }
    }
  }

}
/**
 * Describes the state of any Wi-Fi connection that is active or is in the process
 * of being set up. In the connected state, access to location sensitive fields
 * requires the same permissions as WifiManager.getScanResults. If such access is
 * not allowed, getSSID() will return WifiManager.UNKNOWN_SSID and getBSSID() will
 * return "02:00:00:00:00:00". getApMldMacAddress() will return null. getNetworkId()
 * will return -1. getPasspointFqdn() will return null. getPasspointProviderFriendlyName()
 * will return null. getInformationElements() will return null. getMacAddress()
 * will return "02:00:00:00:00:00".
 */
@Suppress("UNCHECKED_CAST")
abstract class PigeonApiWifiInfo(open val pigeonRegistrar: WifiPigeonProxyApiRegistrar) {
  /**
   * Return the basic service set identifier (BSSID) of the current access point.
   * In case of Multi Link Operation (MLO), the BSSID corresponds to the BSSID
   * of the link used for association.
   *
   * The BSSID may be null, if there is no network currently connected.
   * "02:00:00:00:00:00", if the caller has insufficient permissions to access
   * the BSSID.
   */
  abstract fun getBSSID(pigeon_instance: android.net.wifi.WifiInfo): String

  /**
   * Returns the current frequency in FREQUENCY_UNITS. In case of Multi Link
   * Operation (MLO), returned value is the frequency of the associated link with
   * the highest RSSI.
   */
  abstract fun getFrequency(pigeon_instance: android.net.wifi.WifiInfo): Long

  abstract fun getHiddenSSID(pigeon_instance: android.net.wifi.WifiInfo): Boolean

  abstract fun getIpAddress(pigeon_instance: android.net.wifi.WifiInfo): Long

  /**
   * Returns the current link speed in LINK_SPEED_UNITS. In case of Multi Link
   * Operation (MLO), returned value is the current link speed of the associated
   * link with the highest RSSI.
   */
  abstract fun getLinkSpeed(pigeon_instance: android.net.wifi.WifiInfo): Long

  /**
   * Returns the MAC address used for this connection. In case of Multi Link
   * Operation (MLO), returned value is the Station MLD MAC address.
   */
  abstract fun getMacAddress(pigeon_instance: android.net.wifi.WifiInfo): String

  /**
   * Each configured network has a unique small integer ID, used to identify the
   * network. This method returns the ID for the currently connected network.
   *
   * The networkId may be -1 if there is no currently connected network or if
   * the caller has insufficient permissions to access the network ID.
   */
  abstract fun getNetworkId(pigeon_instance: android.net.wifi.WifiInfo): Long

  /**
   * Returns the received signal strength indicator of the current 802.11 network,
   * in dBm. In case of Multi Link Operation (MLO), returned RSSI is the highest
   * of all associated links.
   *
   * Use WifiManager.calculateSignalLevel(int) to convert this number into an
   * absolute signal level which can be displayed to a user.
   */
  abstract fun getRssi(pigeon_instance: android.net.wifi.WifiInfo): Long

  /**
   * Returns the service set identifier (SSID) of the current 802.11 network.
   *
   * If the SSID can be decoded as UTF-8, it will be returned surrounded by double
   * quotation marks. Otherwise, it is returned as a string of hex digits. The
   * SSID may be WifiManager.UNKNOWN_SSID, if there is no network currently
   * connected or if the caller has insufficient permissions to access the SSID.
   *
   * Prior to Build.VERSION_CODES.JELLY_BEAN_MR1, this method always returned
   * the SSID with no quotes around it.
   */
  abstract fun getSSID(pigeon_instance: android.net.wifi.WifiInfo): String

  companion object {
    @Suppress("LocalVariableName")
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, api: PigeonApiWifiInfo?) {
      val codec = api?.pigeonRegistrar?.codec ?: WifiPigeonCodec()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiInfo.getBSSID", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiInfo
            val wrapped: List<Any?> = try {
              listOf(api.getBSSID(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiInfo.getFrequency", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiInfo
            val wrapped: List<Any?> = try {
              listOf(api.getFrequency(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiInfo.getHiddenSSID", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiInfo
            val wrapped: List<Any?> = try {
              listOf(api.getHiddenSSID(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiInfo.getIpAddress", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiInfo
            val wrapped: List<Any?> = try {
              listOf(api.getIpAddress(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiInfo.getLinkSpeed", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiInfo
            val wrapped: List<Any?> = try {
              listOf(api.getLinkSpeed(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiInfo.getMacAddress", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiInfo
            val wrapped: List<Any?> = try {
              listOf(api.getMacAddress(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiInfo.getNetworkId", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiInfo
            val wrapped: List<Any?> = try {
              listOf(api.getNetworkId(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiInfo.getRssi", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiInfo
            val wrapped: List<Any?> = try {
              listOf(api.getRssi(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.WifiInfo.getSSID", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.wifi.WifiInfo
            val wrapped: List<Any?> = try {
              listOf(api.getSSID(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of WifiInfo and attaches it to [pigeon_instanceArg]. */
  fun pigeon_newInstance(pigeon_instanceArg: android.net.wifi.WifiInfo, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              WifiError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      val pigeon_identifierArg = pigeonRegistrar.instanceManager.addHostCreatedInstance(pigeon_instanceArg)
      val binaryMessenger = pigeonRegistrar.binaryMessenger
      val codec = pigeonRegistrar.codec
      val channelName = "dev.flutter.pigeon.wifi.WifiInfo.pigeon_newInstance"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(pigeon_identifierArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            callback(Result.failure(WifiError(it[0] as String, it[1] as String, it[2] as String?)))
          } else {
            callback(Result.success(Unit))
          }
        } else {
          callback(Result.failure(createConnectionError(channelName)))
        } 
      }
    }
  }

}
/** A simple object for retrieving the results of a DHCP request. */
@Suppress("UNCHECKED_CAST")
abstract class PigeonApiDhcpInfo(open val pigeonRegistrar: WifiPigeonProxyApiRegistrar) {
  abstract fun getDNS1(pigeon_instance: android.net.DhcpInfo): Long

  abstract fun getDNS2(pigeon_instance: android.net.DhcpInfo): Long

  abstract fun getGateway(pigeon_instance: android.net.DhcpInfo): Long

  abstract fun getIpAddress(pigeon_instance: android.net.DhcpInfo): Long

  abstract fun getLeaseDuration(pigeon_instance: android.net.DhcpInfo): Long

  abstract fun getNetmask(pigeon_instance: android.net.DhcpInfo): Long

  abstract fun getServerAddress(pigeon_instance: android.net.DhcpInfo): Long

  companion object {
    @Suppress("LocalVariableName")
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, api: PigeonApiDhcpInfo?) {
      val codec = api?.pigeonRegistrar?.codec ?: WifiPigeonCodec()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.DhcpInfo.getDNS1", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.DhcpInfo
            val wrapped: List<Any?> = try {
              listOf(api.getDNS1(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.DhcpInfo.getDNS2", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.DhcpInfo
            val wrapped: List<Any?> = try {
              listOf(api.getDNS2(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.DhcpInfo.getGateway", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.DhcpInfo
            val wrapped: List<Any?> = try {
              listOf(api.getGateway(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.DhcpInfo.getIpAddress", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.DhcpInfo
            val wrapped: List<Any?> = try {
              listOf(api.getIpAddress(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.DhcpInfo.getLeaseDuration", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.DhcpInfo
            val wrapped: List<Any?> = try {
              listOf(api.getLeaseDuration(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.DhcpInfo.getNetmask", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.DhcpInfo
            val wrapped: List<Any?> = try {
              listOf(api.getNetmask(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.wifi.DhcpInfo.getServerAddress", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.net.DhcpInfo
            val wrapped: List<Any?> = try {
              listOf(api.getServerAddress(pigeon_instanceArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of DhcpInfo and attaches it to [pigeon_instanceArg]. */
  fun pigeon_newInstance(pigeon_instanceArg: android.net.DhcpInfo, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              WifiError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      val pigeon_identifierArg = pigeonRegistrar.instanceManager.addHostCreatedInstance(pigeon_instanceArg)
      val binaryMessenger = pigeonRegistrar.binaryMessenger
      val codec = pigeonRegistrar.codec
      val channelName = "dev.flutter.pigeon.wifi.DhcpInfo.pigeon_newInstance"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(pigeon_identifierArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            callback(Result.failure(WifiError(it[0] as String, it[1] as String, it[2] as String?)))
          } else {
            callback(Result.success(Unit))
          }
        } else {
          callback(Result.failure(createConnectionError(channelName)))
        } 
      }
    }
  }

}
